### ISSUE TITLE
cssFile[file.path] = {styles: file.contents.toString()};

### ISSUE THREAD

**Issue by gvnn** [scniro/gulp-clean-css#17]
Hello,

After upgrading to version `2.1.0` we are starting receiving the following error

```
/Users/gvnn/Projects/thick/make-wally-thick/node_modules/gulp-clean-css/index.js:31
    cssFile[file.path] = {styles: file.contents.toString()};
                                               ^

TypeError: Cannot read property 'toString' of null
    at DestroyableTransform.transform [as _transform] (/Users/gvnn/Projects/thick/make-wally-thick/node_modules/gulp-clean-css/index.js:31:48)
    at DestroyableTransform.Transform._read (/Users/gvnn/Projects/thick/make-wally-thick/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/gvnn/Projects/thick/make-wally-thick/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/gvnn/Projects/thick/make-wally-thick/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/Users/gvnn/Projects/thick/make-wally-thick/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/Users/gvnn/Projects/thick/make-wally-thick/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at Transform.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Transform.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Transform.Readable.push (_stream_readable.js:134:10)
    at Transform.push (_stream_transform.js:128:32)
    at afterTransform (_stream_transform.js:77:12)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Transform.stream._transform (/Users/gvnn/Projects/thick/make-wally-thick/node_modules/gulp-postcss/index.js:19:14)
    at Transform._read (_stream_transform.js:167:10)
```

We pipe to clean-css right after autoprefixer, like this

```
var b = gulp.src(sources)

    b = b.pipe(sasspipe)
        .pipe(postcss([
            autoprefixer({ browsers: ['last 3 versions', '> 5%', 'IE >= 0']})
        ]));

    if(!debug) {
        b = b.pipe(cleanCSS({ compatibility: 'ie8', processImport: false }));
    }

    return b
        .pipe(gulp.dest(dest))
        .pipe(module.size());
```

**Comment by gvnn** [comment]
Just for a little bit of context, we have developed a series of tasks for our internal development pipeline, the code that I posted is used in our repo https://github.com/StudioThick/opine-styles it might be useful for testing.

**Comment by scniro** [comment]
@gvnn yikes! Yes I pushed some changes yesterday in attempts for fix some other stuff. Hang tight as I'll get it up today for you

**Comment by scniro** [comment]
@gvnn also I'm striving to get this done quickly for you but my testing doesn't catch quite everything. Could you do me a favor? Crack open (in your project) `~/node_modules/gulp-clean-css/index.js:31`

and change

    cssFile[file.path] = {styles: file.contents.toString()};

to
    cssFile[file.path] = {styles: file.contents ? file.contents.toString() : file.toString()};

Let me know if that resolves your error?

**Comment by pataar** [comment]
I am having the same error, the fix you provided works.

**Comment by scniro** [comment]
cool I'll get it up soon, are you guys passing files with no contents? couple minutes...

**Comment by scniro** [comment]
[2.1.1](https://www.npmjs.com/package/gulp-clean-css) is up. Can you please pull and confirm if fixed or terribly busted still? 🤓

**Comment by pataar** [comment]
Seems to be working again 👍

**Comment by gvnn** [comment]
Thanks guys 👍  Apologies for the late reply, it was bed time in Australia 🛌

**Comment by nocturnalmonkey** [comment]
Not entirely sure how but I got this issue using v4.0.0?

I had to update `node_modules/gulp-clean-css/index.js` line 24 from:

```
[file.path]: {styles: file.contents.toString()}
```
To
```
[file.path] : {styles: file.contents ? file.contents.toString() : file.toString()}
```

This fixed the issue for me
