### ISSUE TITLE
Error "Ignoring local @import" after update to 2.4.0

### ISSUE THREAD

**Issue by kisonic** [scniro/gulp-clean-css#36]
My file structure:
```
builder
├─ node_modules
└─ gulpfile.js
styles
├─ style1.css
├─ style2.css
└─ style3.css
main.css
```

main.css:
```
@import './styles/style1.css';
@import './styles/style2.css';
@import './styles/style3.css';
```

builder/gulpfile.js:
```
var gulp = require('gulp');
var cleanCss = require('gulp-clean-css');

gulp.task('styles:min', function() {
  gulp.src('../main.css')
    .pipe(cleanCss())
    .pipe(gulp.dest('../'));
});
```

So, after update from 2.3.1 to 2.4.0 I have error:
```
events.js:166
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Ignoring local @import of "styles/style1.css" as resource is missing. Ignoring local @import of "styles/style2.css" as resource is missing. Ignoring local @import of "styles/style3.css" as resource is missing.)
    at DestroyableTransform.emit (events.js:164:17)
    at DestroyableTransform.onerror (/builder/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:189:7)
    at onwriteError (/builder/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:10)
    at onwrite (/builder/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:373:11)
    at WritableState.onwrite (/builder/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:126:5)
    at afterTransform (/builder/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:81:3)
    at TransformState.afterTransform (/builder/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at /builder/node_modules/gulp-clean-css/index.js:36:16
    at /builder/node_modules/clean-css/lib/clean.js:107:9
    at Object.callback (/builder/node_modules/clean-css/lib/reader/read-sources.js:29:9)
    at doApplySourceMaps (/builder/node_modules/clean-css/lib/reader/apply-source-maps.js:61:23)
    at applySourceMaps (/builder/node_modules/clean-css/lib/reader/apply-source-maps.js:33:5)
    at Object.callback (/builder/node_modules/clean-css/lib/reader/read-sources.js:26:12)
    at doInlineImports (/builder/node_modules/clean-css/lib/reader/read-sources.js:191:25)
    at inlineLocalStylesheet (/builder/node_modules/clean-css/lib/reader/read-sources.js:318:10)
    at inlineStylesheet (/builder/node_modules/clean-css/lib/reader/read-sources.js:202:5)
    at doInlineImports (/builder/node_modules/clean-css/lib/reader/read-sources.js:181:14)
    at inlineLocalStylesheet (/builder/node_modules/clean-css/lib/reader/read-sources.js:318:10)
    at inlineStylesheet (/builder/node_modules/clean-css/lib/reader/read-sources.js:202:5)
    at doInlineImports (/builder/node_modules/clean-css/lib/reader/read-sources.js:181:14)
    at inlineLocalStylesheet (/builder/node_modules/clean-css/lib/reader/read-sources.js:318:10)
    at inlineStylesheet (/builder/node_modules/clean-css/lib/reader/read-sources.js:202:5)
    at doInlineImports (/builder/node_modules/clean-css/lib/reader/read-sources.js:181:14)
    at inline (/builder/node_modules/clean-css/lib/reader/read-sources.js:169:10)
    at fromStyles (/builder/node_modules/clean-css/lib/reader/read-sources.js:143:5)
    at fromString (/builder/node_modules/clean-css/lib/reader/read-sources.js:51:10)
    at doReadSources (/builder/node_modules/clean-css/lib/reader/read-sources.js:36:12)
    at readSources (/builder/node_modules/clean-css/lib/reader/read-sources.js:25:10)
    at /builder/node_modules/clean-css/lib/clean.js:97:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by scniro** [comment]
2.4.0 has been deprecated as you should be seeing the message on an install. Please see #31 and #35. Basically I published broken changed and deprecated shortly afterwards. Perhaps I'll just un-publish 2.4.0 as this keeps bubbling up as a problem

**Comment by ShubhamUnique** [comment]
Facing above issue in version gulp-clean-css@3.0.4

**Comment by mlewis22** [comment]
Seconded @ShubhamUnique

**Comment by maxbizbd** [comment]
Same problem in version 3.0.4

**Comment by SirDev** [comment]
Same problem in version 3.4.0. Not sure what's going on here.

**Comment by scniro** [comment]
I tried reproducing this and have indeed gotten the error. This looks related to https://github.com/jakubpawlowicz/clean-css/issues/914. Possible this could be an issue with the library itself.

Passing the following `inline` options seems to fix it...

```
gulp.src('main.css')
  .pipe(cleanCSS({
    inline: ['none']
  }))
  // [...]
```

Would this workaround satisfy the situation?

**Comment by SirDev** [comment]
In the end it was an error with my scss (@import .css file which became a css import which created the error mentioned). perhaps @maxbizbd  can tell you if it works with that workaround?
